CARD_L_COLOR: [0.867, 0.98, 1]


EXAMPLES:
  Приклад 1:
    n: 2
    x: [5, -3, 2, 3]
    y: [17, 11]
    scale: 10
    max_itr: 20

  Приклад 2:
    n: 2
    x: [5, -3, 2, 3]
    y: [17, 11]
    scale: 10
    max_itr: 20

  Приклад 3:
    n: 2
    x: [5, -3, 2, 3]
    y: [17, 11]
    scale: 10
    max_itr: 20

  Введення власної системи:
    n: null
    x: null
    y: null
    scale: null
    max_itr: null


#------for system limitations
MIN_N: 2
MAX_N: 30
MIN_SCALE: 2
MAX_SCALE: 110
MIN_MAX_ITR: 2
MAX_MAX_ITR: 500