CARD_L_COLOR: [0.867, 0.98, 1]


EXAMPLES:
  Приклад 1:
    n: 4
    x:
      - [0, -2.3, -1, 1]
      - [-2.7, 0, 1, -1]
      - [7, -10, 0, 5.4]
      - [11, -14.1, -7, 0]
    y: [-1.77, 0, -3.2, -3.8]

  Приклад 2:
    n: 3
    x:
      - [1, -1, 2]
      - [1, 1, 1]
      - [1, 1, 5]
    y: [1, 11, 12]

  Приклад 3:
    n: 2
    x:
      - [5, -3]
      - [2, 3]
    y: [17, 11]

  Введення власної системи:
    n: null
    x: null
    y: null


#------for system limitations
MIN_N: 2
MAX_N: 15
MIN_SCALE: 2
MAX_SCALE: 110
MIN_MAX_ITR: 2
MAX_MAX_ITR: 500

DEFAULT_EXAMPLE_ID: 0
DEFAULT_METHOD_ID: 0


ANIMATION_DURATION: 0.3