<MainScreen>:
	md_bg_color: self.theme_cls.backgroundColor

	StandartRootBox:
		StandartSelectSection:
		    id: selection_box
		    size_hint: 1, 0.3

		StandartBox:
			size_hint: 1, 0.4

			RestrictedScrollView:
			    clip_behavior: 'clip_children'
				do_scroll_x: False
				do_scroll_y: True


		StandartBox:
		    size_hint: 1, 0.3
		    RestrictedScrollView:
		        id: result_sv
			    clip_behavior: 'clip_children'
				do_scroll_x: True
				do_scroll_y: True