<MainScreen>:
    id: main_screen
	md_bg_color: self.theme_cls.backgroundColor

	StandartRootBox:
		StandartSelectSection:
		    id: selection_box
		    size_hint: 1, 0.3
		    SelectorBox:
		        id:example_selector
		        size_hint_x: None
                width: selection_box.width
		    SelectorBox:
		        id:method_selector
		        size_hint_x: None
                width: selection_box.width
            ThemeSwitch

		StandartBox:
			size_hint: 1, 0.4


			RestrictedScrollView:
			    clip_behavior: 'clip_children'
				do_scroll_x: False
				do_scroll_y: True
				SystemDataBox:
				    id: systemdatabox
				    min_size: main_screen.min_n
				    max_size: main_screen.max_n


		StandartBox:
		    size_hint: 1, 0.3
		    RestrictedScrollView:
		        id: result_sv
			    clip_behavior: 'clip_children'
				do_scroll_x: True
				do_scroll_y: True