<MainScreen>:
    id: main_screen
	md_bg_color: self.theme_cls.backgroundColor

	StandartRootBox:
		StandartSelectSection:
		    id: selection_box
		    size_hint: 1, 0.3
		    MDBoxLayout:
		        spacing: "10dp"
		        MDBoxLayout:
		            size_hint: 0.87, 1
		            orientation: "vertical"
		            spacing: "8dp"

                    SelectorBox:
                        id:example_selector
                        #size_hint_x: None
                        #width: selection_box.width
                    SelectorBox:
                        id:method_selector
                        #size_hint_x: None
                        #width: selection_box.width
                MDBoxLayout:
                	size_hint: 0.13, 1
                    ExitBtn:
                    	size_hint: 1, 1

            MDBoxLayout:
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                size_hint: None, None
                adaptive_width: True
                adaptive_height: True
                spacing: "10dp"
                ThemeSwitch
                ParallelSwitch:
                    id: parallel_switch

		StandartBox:
			size_hint: 1, 0.4

			RestrictedScrollView:
			    clip_behavior: 'clip_children'
				do_scroll_x: False
				do_scroll_y: True
				SystemDataBox:
				    id: systemdatabox
				    min_size: main_screen.min_n
				    max_size: main_screen.max_n


		StandartBox:
		    size_hint: 1, 0.3
		    RestrictedScrollView:
		        id: result_sv
			    clip_behavior: 'clip_children'
				do_scroll_x: True
				do_scroll_y: True