<SystemDataBox>:
    id: system_data_box
    orientation: "vertical"
    adaptive_height: True
    spacing: "5sp"

    ParameterBox:
        id: size_param_box
        SizeParamExtra:
            id: size_param
            on_apply: root.change_system_size(self.value)
            min_value: root.min_size
            max_value: root.max_size



	ParameterBox:
        id: system_input_box
        size_hint: 1, None
        height: system.height
        NestedHorizontalScrollView:
            do_scroll_y: False
            do_scroll_x: True

            BoxLayout:
                size_hint_x: None
                height: self.minimum_height
                width: max(system_input_box.width, system.minimum_width)

                Widget:
                    size_hint_x: 1

                SystemBox:
                    id: system

                Widget:
                    size_hint_x: 1
	ParameterBox:
		id: extra_params_box





