<ParameterText>:
	mode: "filled"
	required: self.is_required

	pos_hint: {"center_x": 0.5, "center_y": 0.5}

	MDTextFieldHelperText:
	    id: hint_text
		theme_font_size: "Custom"
		font_size: "15sp"
		text: "Некоректні дані"
		mode: "persistent"	#!!!on_error mode changes the text color to black, when user changes app theme from Dark to Light, KiviMD problem
		text_color_focus: [0, 0, 0, 0]
		text_color_normal:[0, 0, 0, 0]


<IntParameterText>:
    input_filter: 'int'


<BaseParamLayout>:
	size_hint_y: None
	on_size: self.orientation_check()
	padding: ["30dp",0,"30dp",0]


<StandartParam>:
    id: param_root

	ParameterText:
		id: input
		on_text: param_root.value = self.text
		min_value: param_root.min_value
		max_value: param_root.max_value
		forbid_negative: param_root.forbid_negative_param
		can_be_zero: param_root.can_be_zero

		input_filter: param_root.input_type
		MDTextFieldHintText:
			text: param_root.hint

<PreconditionParams>:
    adaptive_height: True
    orientation: "vertical"
    MDBoxLayout:
	    size_hint_y: None
	    height: 70
        padding: (30, 10, 30, 0)

        SelectorBox:
            id: precondition_mtd
            size_hint: 1,1
            btn_color_is_custom: True
            btn_custom_color: [0.318, 0.569, 0.792, 1]

    IntParam:
        id: scale
        forbid_negative_param: True
        hint: "Множник матриць"
        min_value: root.min_scale
        max_value: root.max_scale

<ClassicMethodsParam>:
    orientation: "vertical"
    padding: (0, 10, 0, 0)

    BaseParamLayout:
        padding: 0
        FloatParam:
            id: eps
            forbid_negative_param: True
            can_be_zero: True
            hint: "Похибка"
            min_value: root.min_eps
            max_value: root.max_eps

        IntParam:
            id: limit
            forbid_negative_param: True
            hint: "Ліміт ітерацій"
            min_value: root.min_itr
            max_value: root.max_itr

    PreconditionParams:
        id: precond_param

    MDWidget:
        id: dummy
	    size_hint_y: None
        height: dp(10)

<MonteParams>:
    orientation: "vertical"
    padding: (0, 10, 0, 0)

    FloatParam:
        id: eps
        min_value: root.min_eps
        max_value: root.max_eps
        forbid_negative_param: True
        hint: "Похибка"

    FloatParam:
        id: alpha
        min_value: root.min_alpha
        max_value: root.max_alpha
        forbid_negative_param: True
        hint: "Рівень значущості"

    PreconditionParams:
        id: precond_param

    MDWidget:
        id: dummy
	    size_hint_y: None
        height: dp(10)


<SizeParamExtra>:
    MDBoxLayout:
        id: size_box
        spacing:0
        padding:0

        SizeParam:
            id: size_param
            on_value: root._on_inner_value(self.value)
            padding: 0
            min_value: root.min_value
            max_value: root.max_value

    MDBoxLayout:
        id:buttons_box
        spacing: "6dp"
        SizableFabBtn:
            id: plus_button
            ripple_scale: 0
            icon: "plus"
            on_release: root.increment()

        SizableFabBtn:
            id: minus_button
            ripple_scale: 0
            icon: "minus"
            on_release: root.decrement()

        SizableFabBtn:
            id: size_apply
            ripple_scale: 0
            icon: "check"
            on_release: root.dispatch_apply_action()
        SizableFabBtn:
            id: clear
            ripple_scale: 0
            icon: "delete"
            on_release: root.dispatch_clear_action()
