<ParameterText>:
	mode: "filled"
	required: self.is_required

	pos_hint: {"center_x": 0.5, "center_y": 0.5}

	MDTextFieldHelperText:
	    id: hint_text
		theme_font_size: "Custom"
		font_size: "15sp"
		text: "Некоректні дані"
		mode: "persistent"	#!!!on_error mode changes the text color to black, when user changes app theme from Dark to Light, KiviMD problem
		text_color_focus: [0, 0, 0, 0]
		text_color_normal:[0, 0, 0, 0]


<IntParameterText>:
    input_filter: 'int'


<BaseParamLayout>:
	size_hint_y: None
	on_size: self.orientation_check()
	padding: ["30dp",0,"30dp",0]


<StandartParam>:
    id: param_root

	ParameterText:
		id: input
		on_text: param_root.value = self.text
		min_value: root.min_value
		max_value: root.max_value
		forbid_negative: param_root.forbid_negative_param
		input_filter: param_root.input_type
		MDTextFieldHintText:
			text: param_root.hint


<ClassicMethodsParam>:
    padding: 0

    MDBoxLayout:
        IntParam:
            id: scale
            forbid_negative_param: True
            hint: "Множник матриць"
            min_value: root.min_scale
            max_value: root.max_scale

    MDBoxLayout:
        IntParam:
            id: limit
            forbid_negative_param: True
            hint: "Ліміт ітерацій"
            min_value: root.min_itr
            max_value: root.max_itr

<SizeParamExtra>:
    MDBoxLayout:
        id: size_box
        spacing:0
        padding:0

        SizeParam:
            id: size_param
            on_value: root._on_inner_value(self.value)
            padding: 0
            min_value: root.min_value
            max_value: root.max_value

    MDBoxLayout:
        id:buttons_box
        spacing: "6dp"
        SizableFabBtn:
            id: plus_button
            icon: "plus"
            on_release: root.increment()

        SizableFabBtn:
            id: minus_button
            icon: "minus"
            on_release: root.decrement()

        SizableFabBtn:
            id: size_apply
            icon: "check"
            on_release: root.dispatch_apply_action()

<SystemFloatParam>:
    hint: "c:"
	padding: [0,0,0,0]