<SystemBox>:
    orientation: "vertical"

    spacing: 0

    size_hint_x: None
    width: self.minimum_width

    size_hint_y: None
    height: self.minimum_height

    MDBoxLayout:
        padding: [30,0,0,0]
        size_hint_x: None
        width: self.minimum_width
        spacing: 20

        size_hint_y: None
        height: self.minimum_height
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam


    MDBoxLayout:
        padding: [30,0,0,0]
        size_hint_x: None
        width: self.minimum_width
        spacing: 20

        size_hint_y: None
        height: self.minimum_height
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam
        SystemFloatParam

