<SystemLabel>:
    theme_font_size: "Custom"
    font_size: self.font

    size_hint_x: None
    width:self.texture_size[0]

    text_size: None, None

<SystemBrace>:
    size_hint_x: None
    width: dp(20)

<SystemRow>:
    spacing: 5

    size_hint_x: None
    width: self.minimum_width
    size_hint_y: None
    height: self.minimum_height


<SystemBox>:
    orientation: "horizontal"
    padding: [30, 0, 30, 0]
    size_hint_x: None
    width: self.minimum_width
    size_hint_y: None
    height: self.minimum_height
    spacing:5

    SystemBrace:
        id: brace

    MDBoxLayout:
        id: equations_box
        spacing: 0
        orientation: "vertical"
        size_hint_x: None
        width: self.minimum_width
        size_hint_y: None
        height: self.minimum_height








