<SystemLabel>:
    theme_font_size: "Custom"
    font_size: self.font

    size_hint_x: None
    adaptive_width: True

    text_size: None, None

<SystemBrace>:
    size_hint_x: None
    width: dp(20)

<SystemCoef>:
    size_hint_x: None
    size_hint_y: None
    height: "30dp"
    width: "85dp"
    required: True
    input_filter: 'float'
    theme_font_size: "Custom"
    font_size: self.height * 0.8
    halign: "center"


<SystemRow>:
    spacing: 5

    size_hint_x: None
    width: self.minimum_width
    size_hint_y: None
    height: self.minimum_height


<SystemBox>:
    orientation: "horizontal"
    padding: [30, 0, 30, 0]
    size_hint_x: None
    width: self.minimum_width
    size_hint_y: None
    height: self.minimum_height
    spacing:5

    SystemBrace:
        id: brace

    MDBoxLayout:
        id: equations_box
        spacing: 10
        padding: 10
        orientation: "vertical"
        size_hint_x: None
        width: self.minimum_width
        size_hint_y: None
        height: self.minimum_height








