<ControlButton>:
	icon: "pencil-outline"
	on_release: self.parent.dispatch_btn_click()


<LabelArea>:
	md_bg_color: self.theme_cls.surfaceContainerLowColor
	radius: [15]

	pos_hint: {"center_x": 0.5, "center_y": 0.5}
	size_hint: 0.8, 1

	canvas.before:
		Color:
			rgba: 0, 0, 0, 0.2
		BoxShadow:
			pos: root.pos
			size:  root.size[0]/1.005, root.size[1]/1.3
			offset: [dp(root.size[0]*0.4/100), dp(root.size[1]*0.5/100)]
			spread_radius: [0, 0]
			border_radius: [root.radius[0]+dp(5), root.radius[0]+dp(5),root.radius[0]+dp(5),root.radius[0]+dp(5)]
			blur_radius: dp(root.size[1]/3)


<ControlLabel>:
	theme_font_size : "Custom"
	halign: "center"
	valign: "middle"
	padding: [0,0,0,0]


<ControlBox>:
    pos_hint: {"center_x": 0.5, "center_y": 0.5}


<SelectButton>:
    on_release: self.build_menu(self)


<SelectorBox>:
	size_hint: 1, 0.35
    spacing: "10dp"



